### ISSUE TITLE
Reason for setting up segment reduction

### ISSUE THREAD

**Issue by sha256feng** [lrjconan/LanczosNetwork#5]
In the "setup.sh" file, the program called a python script to do segment reduction based on Pytorch version and whether Cuda is available. I have acquainted myself with some knowledge on C++ and Cuda extension of Pytorch. Yet I still had difficulty understanding why we need to have the segment reduction extension. Can you explain a bit?

Thanks,
Shasha

**Comment by lrjconan** [comment]
Hi, sorry for the late response.
You can ignore the segment reduction part as it is legacy code for implementing the memory-efficient version of GNN which requires something like `unsorted_seg_sum` function as in Tensorflow. 
Pytorch now supports unsorted_seg_sum via scatter_add.

**Comment by lrjconan** [comment]
> In the "setup.sh" file, the program called a python script to do segment reduction based on Pytorch version and whether Cuda is available. I have acquainted myself with some knowledge on C++ and Cuda extension of Pytorch. Yet I still had difficulty understanding why we need to have the segment reduction extension. Can you explain a bit?
> 
> Thanks,
> Shasha

Hi, sorry for the late response.
You can ignore the segment reduction part as it is legacy code for implementing the memory-efficient version of GNN which requires something like unsorted_seg_sum function as in Tensorflow.
Pytorch now supports unsorted_seg_sum via scatter_add.
