### ISSUE TITLE
Export Python environment yml

### ISSUE THREAD

**Issue by sha256feng** [lrjconan/LanczosNetwork#7]
Despite the dependence said on 'readme.md' page (`scipy`, `sklearn`, `numpy`, `pytorch`), I also found several other packages that require installation: `pyyaml`, `easydict`, `tqdm`, `tensorboardx`. It might be a good idea to export the python environment to yml as shown in this link [https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file]. 

[https://github.com/lrjconan/LanczosNetwork]
""" 
Dependencies
Python 3, PyTorch(1.0), numpy, scipy, sklearn
"""

**Comment by lrjconan** [comment]
Thanks for your suggestion! Will do.
